<div class="container">
<div class="header clearfix">
        <br>
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" ><a href="/">Home</a></li>
            <li role="presentation" class="active"><a href="#">About</a></li>
            <li role="presentation"><a href="/contact">Contact</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Classes WEB</h3>
      </div>
       <hr>
       <br>
  <h1>About</h1>
  <section>
    <div class="row">
      <div class="col-12">
        <h2>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reiciendis unde temporibus exercitationem </h2>
      </div>
    </div>
  </section>
</div>