<div class="page-header">
    <div class="container">
    <h1>TechLaunch.IO FVI</h1>
    <div class="jumbotron">
        <div class="container">
            <h1>Classes  2018</h1>
            <p>Contents ...</p>
            <p>
                <a class="btn btn-primary btn-lg" href="/home">Click Here</a>
            </p>
            <p>
                <a class="btn btn-secondary btn-lg" href="/signup">Don't have a account. SignUp here</a>
            </p>
        </div>
    </div>
    <p>In this website you will find all about the WEB Developer Course</p>
    </div>
</div>



 <section>
 

         <div class="row">
             <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
             <div class="container">
             <h2>Classes</h2>  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner ">
      <div class="item active col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <img src="img/p1.jpg" alt="Los Angeles" style="width:100%;">
      </div>

      <div class="item col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <img src="img/p2.jpg" alt="Chicago" style="width:100%;">
      </div>
    
      <div class="item col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <img src="img/p3.jpg" alt="New york" style="width:100%;">
      </div>
      <div class="item col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <img src="img/p4.jpg" alt="Chicago" style="width:100%;">
      </div>
    
      <div class="item col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <img src="img/p5.jpg" alt="New york" style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
             </div>
             
         </div>
     </div>
 </section>
<p></p>
